Disable-WindowsOptionalFeature -Online -FeatureName ServerManager-Core-RSAT-Feature-Tools
Disable-WindowsOptionalFeature -Online -FeatureName IIS-LegacySnapIn
Disable-WindowsOptionalFeature -Online -FeatureName IIS-ASP
Disable-WindowsOptionalFeature -Online -FeatureName IIS-ASPNET45
Disable-WindowsOptionalFeature -Online -FeatureName IIS-LegacyScripts
Disable-WindowsOptionalFeature -Online -FeatureName IIS-WMICompatibility
Disable-WindowsOptionalFeature -Online -FeatureName IIS-Metabase
Disable-WindowsOptionalFeature -Online -FeatureName IIS-IIS6ManagementCompatibility
Disable-WindowsOptionalFeature -Online -FeatureName IIS-ManagementService
Disable-WindowsOptionalFeature -Online -FeatureName IIS-ManagementScriptingTools
Disable-WindowsOptionalFeature -Online -FeatureName IIS-ManagementConsole
Disable-WindowsOptionalFeature -Online -FeatureName IIS-WebServerManagementTools
Disable-WindowsOptionalFeature -Online -FeatureName IIS-HttpCompressionStatic
Disable-WindowsOptionalFeature -Online -FeatureName IIS-Performance
Disable-WindowsOptionalFeature -Online -FeatureName IIS-RequestFiltering
Disable-WindowsOptionalFeature -Online -FeatureName IIS-IISCertificateMappingAuthentication
Disable-WindowsOptionalFeature -Online -FeatureName IIS-ClientCertificateMappingAuthentication
Disable-WindowsOptionalFeature -Online -FeatureName IIS-WindowsAuthentication
Disable-WindowsOptionalFeature -Online -FeatureName IIS-Security
Disable-WindowsOptionalFeature -Online -FeatureName IIS-ODBCLogging
Disable-WindowsOptionalFeature -Online -FeatureName IIS-HttpTracing
Disable-WindowsOptionalFeature -Online -FeatureName IIS-LoggingLibraries
Disable-WindowsOptionalFeature -Online -FeatureName IIS-HttpLogging
Disable-WindowsOptionalFeature -Online -FeatureName IIS-HealthAndDiagnostics
Disable-WindowsOptionalFeature -Online -FeatureName IIS-ISAPIFilter
Disable-WindowsOptionalFeature -Online -FeatureName IIS-ISAPIExtensions
Disable-WindowsOptionalFeature -Online -FeatureName IIS-NetFxExtensibility45
Disable-WindowsOptionalFeature -Online -FeatureName IIS-ApplicationDevelopment
Disable-WindowsOptionalFeature -Online -FeatureName IIS-HttpRedirect
Disable-WindowsOptionalFeature -Online -FeatureName IIS-HttpErrors
Disable-WindowsOptionalFeature -Online -FeatureName IIS-DirectoryBrowsing
Disable-WindowsOptionalFeature -Online -FeatureName IIS-DefaultDocument
Disable-WindowsOptionalFeature -Online -FeatureName IIS-StaticContent
Disable-WindowsOptionalFeature -Online -FeatureName IIS-CommonHttpFeatures
Disable-WindowsOptionalFeature -Online -FeatureName IIS-WebServer
Disable-WindowsOptionalFeature -Online -FeatureName IIS-WebServerRole